---
apiVersion: v1
kind: Namespace
metadata:
  name: keda-prometheus-guidance
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  namespace: keda-prometheus-guidance
  name: prometheus-sampleapp-svc
  labels:
    app: sample-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: sample-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: keda-prometheus-guidance
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      name: sample-app
      labels:
        app: sample-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '80'
    spec:
      containers:
        - name: sample-app
          image: {SAMPLE_APP_ECR}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
      